### ISSUE TITLE
Package-Private Factories

### ISSUE THREAD

**Issue by katzer** [stCarolas/enriched-beans#2]
Would be nice to have the ability to control the access-level of the factory class: public or package-private.

https://github.com/stCarolas/enriched-beans/blob/master/processor/src/main/java/com/github/stcarolas/enrichedbeans/processor/EnrichProcessor.java#L68

**Comment by stCarolas** [comment]
Implemented as global parameter
readme - https://github.com/stCarolas/enriched-beans#factory-customization
commit - https://github.com/stCarolas/enriched-beans/commit/1303aa3523b9dabc0cbeb3073d78dc77fb676709
